a = input("enter number 1 :" )
b = input("enter number 2 :" )
c = int(a)
d = int(b)
print("Number 1 is ",a)
print("Number 2 is ", b)
print("sum is ",a+b)
print("Sum is ",c+d)
e =int(input("enter number 1 :"))
print(e)