s=set()
num =int(input("Enter num"))
s.add(num)
num1 =int(input("Enter num"))
s.add(num1)
num2 =int(input("Enter num"))
s.add(num2)
num3 =int(input("Enter num"))
s.add(num3)
num4 =int(input("Enter num"))
s.add(num4)
num5 =int(input("Enter num"))
s.add(num5)
print(s)